"""Frozen vocabulary + data model for the decision ledger and finding frontmatter.

This module is the source of truth for the two closed axes, the actor enum, and the
violation-code vocabulary that ``genome docs check`` enforces. It is
**import-side-effect-free** and has **no** dependency on :mod:`genome.db` or any database
driver (plan §3 / Task 3): ``python -c "import genome.docs.model"`` must not import DuckDB
or SQLCipher.

The two closed axes are orthogonal (plan §0 resolution #2):

* ``status`` — the *lifecycle* axis (:data:`STATUS_VOCAB`): where a decision sits in its
  life. Transitions are append-then-flip, never an in-place content edit — the intent of
  locked decision #7, relocated to the validator gate because a markdown ledger has no
  transaction.
* ``kind`` — the *granularity* axis (:data:`KIND_VOCAB`), the former ``grain`` column.
  ``tactical`` lives here, **not** on the status axis, so a tactical decision still carries
  a full lifecycle ``status`` and can be recorded as superseded/reversed.

The violation codes live here (not in :mod:`genome.docs.validator`) so the parsers can tag
their errors with a code without importing the validator — :mod:`genome.docs.validator`
re-exports them, so ``validator.DUPLICATE_DEC_ID`` still resolves.
"""

from __future__ import annotations

from dataclasses import dataclass

# ── Closed vocabularies (validator enforces membership) ──────────────────────

STATUS_VOCAB: frozenset[str] = frozenset({"active", "superseded", "reversed", "deferred"})
"""Lifecycle states. ``active`` is current; ``superseded``/``reversed`` require a
resolving ``superseded_by`` pointer; ``deferred`` is parked."""

KIND_VOCAB: frozenset[str] = frozenset({"architectural", "tactical"})
"""Granularity axis (former ``grain``). ``architectural`` ≈ a locked design decision;
``tactical`` ≈ an implementation-level choice."""

FINDING_TYPE_VOCAB: frozenset[str] = frozenset({"observation", "decision", "both"})
"""What a finding records, declared in its frontmatter ``type`` key."""

CANONICAL_ACTORS: frozenset[str] = frozenset(
    {
        "ClaudeCodeVerification",
        "ClaudeCodeTestingBugs",
        "ClaudeCodePlanning",
        "ClaudeCodeDevelopment",
        "VSC-User",
    },
)
"""The five canonical actor names (CLAUDE.md five-actor model)."""

LEGACY_ACTOR_MAP: dict[str, str] = {
    "VSC-Claude": "ClaudeCodeDevelopment",
    "VSC-ClaudeCodeDevelopment": "ClaudeCodeDevelopment",
    "VSC-ClaudeCode": "ClaudeCodeDevelopment",
    "VSC-ClaudeCodePlanning": "ClaudeCodePlanning",
    "AI-Claude": "ClaudeCodeDevelopment",
}
"""Legacy → canonical spellings live in tracked history (CHANGELOG, older findings).
Applied so existing provenance validates; an unmapped novel name is a hard fail."""

# ── Identifier conventions ───────────────────────────────────────────────────

#: The ledger file, relative to the repo root. Markdown, *not* a DB table.
LEDGER_FILENAME: str = "MEMORY.md"

#: Marker comments delimiting the generated findings-index table in the findings
#: README. ``build-index`` rewrites only the span between them; everything else in
#: the README is hand-authored and preserved.
INDEX_BEGIN_MARKER: str = "<!-- BEGIN findings-index (generated by `genome docs build-index`) -->"
INDEX_END_MARKER: str = "<!-- END findings-index -->"

# ── Dimensions + violation codes (shared by the parsers and the validator) ───

CAPTURE: str = "capture"
RETRIEVAL: str = "retrieval"
LIFECYCLE: str = "lifecycle"

# CAPTURE
MISSING_FRONTMATTER: str = "MISSING_FRONTMATTER"
MALFORMED_FRONTMATTER: str = "MALFORMED_FRONTMATTER"
DECISION_WITHOUT_DEC_ROW: str = "DECISION_WITHOUT_DEC_ROW"
# RETRIEVAL
STALE_INDEX: str = "STALE_INDEX"
# LIFECYCLE
MALFORMED_LEDGER_ROW: str = "MALFORMED_LEDGER_ROW"
DUPLICATE_DEC_ID: str = "DUPLICATE_DEC_ID"
NON_MONOTONIC_DEC_ID: str = "NON_MONOTONIC_DEC_ID"
BAD_STATUS_VOCAB: str = "BAD_STATUS_VOCAB"
BAD_KIND_VOCAB: str = "BAD_KIND_VOCAB"
BAD_TYPE_VOCAB: str = "BAD_TYPE_VOCAB"
SUPERSEDED_WITHOUT_POINTER: str = "SUPERSEDED_WITHOUT_POINTER"
MULTIPLE_SUPERSEDERS: str = "MULTIPLE_SUPERSEDERS"
ORPHAN_SUPERSESSION: str = "ORPHAN_SUPERSESSION"
UNRESOLVED_CROSS_REF: str = "UNRESOLVED_CROSS_REF"
NON_CANONICAL_ACTOR: str = "NON_CANONICAL_ACTOR"
INPLACE_CONTENT_EDIT: str = "INPLACE_CONTENT_EDIT"
MISSING_PROVENANCE: str = "MISSING_PROVENANCE"
COPIED_ANCHOR_NUMBER: str = "COPIED_ANCHOR_NUMBER"

CODE_DIMENSION: dict[str, str] = {
    MISSING_FRONTMATTER: CAPTURE,
    MALFORMED_FRONTMATTER: CAPTURE,
    DECISION_WITHOUT_DEC_ROW: CAPTURE,
    STALE_INDEX: RETRIEVAL,
    MALFORMED_LEDGER_ROW: LIFECYCLE,
    DUPLICATE_DEC_ID: LIFECYCLE,
    NON_MONOTONIC_DEC_ID: LIFECYCLE,
    BAD_STATUS_VOCAB: LIFECYCLE,
    BAD_KIND_VOCAB: LIFECYCLE,
    BAD_TYPE_VOCAB: LIFECYCLE,
    SUPERSEDED_WITHOUT_POINTER: LIFECYCLE,
    MULTIPLE_SUPERSEDERS: LIFECYCLE,
    ORPHAN_SUPERSESSION: LIFECYCLE,
    UNRESOLVED_CROSS_REF: LIFECYCLE,
    NON_CANONICAL_ACTOR: LIFECYCLE,
    INPLACE_CONTENT_EDIT: LIFECYCLE,
    MISSING_PROVENANCE: LIFECYCLE,
    COPIED_ANCHOR_NUMBER: LIFECYCLE,
}
"""Maps every violation code to its CAPTURE / RETRIEVAL / LIFECYCLE dimension."""


def canonicalize_actor(name: str) -> str | None:
    """Map a raw actor token to its canonical name, or ``None`` if unknown.

    Returns the input unchanged when already canonical; applies
    :data:`LEGACY_ACTOR_MAP` otherwise; returns ``None`` for a token that is neither
    canonical nor mapped (the validator turns ``None`` into a hard fail).
    """
    if name in CANONICAL_ACTORS:
        return name
    return LEGACY_ACTOR_MAP.get(name)


# ── Frozen records ───────────────────────────────────────────────────────────


@dataclass(frozen=True, slots=True)
class Frontmatter:
    """The parsed ``---``-fenced block atop a finding. Authoritative for the
    supersession edge (plan §0 resolution #4)."""

    type: str
    """One of :data:`FINDING_TYPE_VOCAB`."""
    status: str
    """One of :data:`STATUS_VOCAB`."""
    actors: tuple[str, ...]
    """Canonical actor names (post legacy-map)."""
    date: str
    """ISO-8601 date (``YYYY-MM-DD``)."""
    supersedes: tuple[str, ...] = ()
    """finding-id and/or DEC-id this finding's decision replaces."""
    superseded_by: tuple[str, ...] = ()
    """finding-id and/or DEC-id that replaces this finding's decision."""


@dataclass(frozen=True, slots=True)
class LedgerRow:
    """One row of the ``MEMORY.md`` decision table. Content columns are immutable
    once written; only ``status``/``superseded_by`` transition (insert-then-flip)."""

    dec: str
    """``DEC-NNNN`` — unique, monotonic."""
    kind: str
    """One of :data:`KIND_VOCAB`."""
    date: str
    """ISO-8601 date."""
    status: str
    """One of :data:`STATUS_VOCAB`."""
    actors: tuple[str, ...]
    """Canonical actor names."""
    provenance: str
    """Verbatim source (``PR #93``, ``git:<sha>``) or the literal ``unknown``."""
    decision: str
    """Free text; raw ``|`` is escaped. Anchors are *referenced*, never copied."""
    detail_link: str
    """Path/anchor to the canonical detail (a finding, a CLAUDE.md obs #N)."""
    superseded_by: str | None = None
    """DEC-id of the superseding decision; required when status is
    ``superseded``/``reversed``, ``None`` otherwise."""


@dataclass(frozen=True, slots=True)
class CheckViolation:
    """A single hard-fail emitted by :func:`genome.docs.validator.check`."""

    dimension: str
    """``capture`` | ``retrieval`` | ``lifecycle``."""
    code: str
    """Stable machine code, e.g. ``MISSING_FRONTMATTER``, ``ORPHAN_SUPERSESSION``."""
    location: str
    """Where it lives — a file path + line, or a DEC id."""
    message: str
    """Human-readable explanation printed by ``genome docs check``."""


@dataclass(frozen=True, slots=True)
class CheckReport:
    """The outcome of a ``genome docs check`` run."""

    violations: tuple[CheckViolation, ...]

    @property
    def ok(self) -> bool:
        """True iff there are no violations (drives the CLI exit code)."""
        return not self.violations

    def by_dimension(self, dimension: str) -> tuple[CheckViolation, ...]:
        """All violations for one of CAPTURE / RETRIEVAL / LIFECYCLE."""
        return tuple(v for v in self.violations if v.dimension == dimension)


@dataclass(frozen=True, slots=True)
class IndexResult:
    """The outcome of a ``genome docs build-index`` run."""

    changed: bool
    """True when the rendered index differs (normalize-then-compare) from committed."""
    rendered: str
    """The full README text with the regenerated marker block."""
    findings_indexed: int
    """Number of findings folded into the index table."""
    cross_links_derived: int
    """Number of supersession cross-links derived from finding frontmatter."""
